name: android-tests-browserstack
on: [push]
branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v2
        - uses: actions/setup-node@v1
          with:
            node-version: 16.13.0
        - name: Install
          run: npm install
        - name: Run e2e tests
          env: 
            BROWSERSTACK_USER: ${{ secrets.BROWSERSTACK_USER }}
            BROWSERSTACK_KEY: ${{ secrets.BROWSERSTACK_KEY }}
          run: npm run android-bs-test
        - uses: actions/upload-artifact@v1
          if: failure()
          with:
            name: logs
            path: logs
